updates: fixes to scripts script

diff --git a/updates.d/60-scripts b/updates.d/60-scripts
--- a/updates.d/60-scripts
+++ b/updates.d/60-scripts
@@ -29,11 +29,11 @@ SCRIPT_NAME=$(basename $0)
 for s in $SIMSTICK_UPDATE_PATH/scripts.d/???*; do
 		SCRIPT_NAME=$(basename $s)
 		echo -n "Checking $SCRIPT_NAME..."
-		if [ -L "~/bin/$SCRIPT_NAME" ]; then
+		if [ -L "$HOME/bin/$SCRIPT_NAME" ]; then
 				echo "already installed"
 		else
 				echo -n "installing..."
-				ln -s $s ~/bin/$(SCRIPT_NAME) || echo "FAILED" && exit -1
+				ln -s $s "$HOME/bin/$SCRIPT_NAME" || ( echo "FAILED" && exit -1 )
 				echo "done"
 		fi
 fi
